[1]
host = "192.168.1.201"           # 激光雷达IP
port = 2111                      # 激光雷达端口
same_origin_offset_x = 0         # 相对同一原点偏移X,单位mm
same_origin_offset_y = 3660      # 相对同一原点偏移Y,单位mm
diff_origin_offset_x = 0         # 相对不同原点偏移X,单位mm(不同原点定义:左侧为左侧激光地面上,右侧为右侧激光地面上,上侧为左右原点的中心线地面上)
diff_origin_offset_y = 3660      # 相对不同原点偏移Y,单位mm    
type = "120"                     # 激光型号
install_orietation = "left"      # 激光安装方向
start_angle_direction = 1        # 激光起始角度方向,0为0度在下方,1为0度在上方,2为0度朝右边,3为0度朝左边,都是面对激光正面逆时针0-180
start_angle = 35                  # 激光起始角度
stop_angle = 135                 # 激光结束角度

[2]
host = "192.168.1.202"
port = 2111
same_origin_offset_x = 0
same_origin_offset_y = 2635
diff_origin_offset_x = 0
diff_origin_offset_y = 2635
type = "120"
install_orietation = "left"
start_angle_direction = 1
start_angle = 35
stop_angle = 135

[3]
host = "192.168.1.203"
port = 2111
same_origin_offset_x = 0
same_origin_offset_y = 1400
diff_origin_offset_x = 0
diff_origin_offset_y = 1400
type = "120"
install_orietation = "left"
start_angle_direction = 1
start_angle = 35
stop_angle = 135

[4]
host = "192.168.1.204"
port = 2111
same_origin_offset_x = 3950
same_origin_offset_y = 3675
diff_origin_offset_x = 0
diff_origin_offset_y = 3675
type = "120"
install_orietation = "right"
start_angle_direction = 1
start_angle = 35
stop_angle = 135

[5]
host = "192.168.1.205"
port = 2111
same_origin_offset_x = 3950
same_origin_offset_y = 2630
diff_origin_offset_x = 0
diff_origin_offset_y = 2630
type = "120"
install_orietation = "right"
start_angle_direction = 1
start_angle = 35
stop_angle = 135

[6]
host = "192.168.1.206"
port = 2111
same_origin_offset_x = 3950
same_origin_offset_y = 1400
diff_origin_offset_x = 0
diff_origin_offset_y = 1400
type = "120"
install_orietation = "right"
start_angle_direction = 1
start_angle = 35
stop_angle = 135
