[0]
sn = 0
type = "out_fx"
x_position = 1085
z_position = 4750
spray_num = 8
tracking = 0
y_move_min = 0
y_move_max = 300
axis_type = ["z", "y", "x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8"]
spray_radius = 0
x_status_offset = 100
out_front_x_offset = 150
out_after_x_offset = 280
in_front_x_offset = 100
in_after_x_offset = 100
out_up_y_offset = 200
out_down_y_offset = 200
in_up_y_offset = 100
in_down_y_offset = 100
out_z_front_offset = 200
out_z_after_offset = 200
in_z_front_offset = 100
in_z_after_offset = 100
z_back_speed = 0
x_pos_speed = 500
x_recip_speed = 120
y_pos_speed = 100
y_recip_speed = 200
z_zeroing_speed = 100
outside_total_cycles = 1
inside_total_cycles = 1
recip_reduce_distance = 100
install_orietation = "left"
max_limit_speed = [250, 500, 500]
min_limit_pos = [0, 0, 0]
max_limit_pos = [700, 300, 900]
origin_pos = [1170, 1420, 1670, 1920, 2170, 2420, 2670, 2920]
safe_pos = [0, 0, 0]

[1]
sn = 1
type = "xn_side"
x_position = 1035
z_position = 8570
spray_num = 6
tracking = 0
y_move_min = 0
y_move_max = 500
axis_type = ["z", "y1", "x1", "r1", "y2", "x2", "r2", "y3", "x3", "r3", "y4", "x4", "r4", "y5", "x5", "r5", "y6", "x6", "r6"]
spray_radius = 0
x_status_offset = 100
out_front_x_offset = 150
out_after_x_offset = 280
in_front_x_offset = 100
in_after_x_offset = 100
out_up_y_offset = 150
out_down_y_offset = 150
in_up_y_offset = 100
in_down_y_offset = 100
out_z_front_offset = 200
out_z_after_offset = 200
in_z_front_offset = 100
in_z_after_offset = 100
z_back_speed = 15
x_pos_speed = 500
x_recip_speed = 120
y_pos_speed = 100
y_recip_speed = 200
z_zeroing_speed = 200
outside_total_cycles = 2
inside_total_cycles = 2
recip_reduce_distance = 100
install_orietation = "left"
max_limit_speed = [250, 500, 500, 160]
min_limit_pos = [0, 0, 0, -180]
max_limit_pos = [900, 900, 900, 180]
origin_pos = [1120, 1420, 1720, 2020, 2320, 2620]
safe_pos = [0, 0, 0, 0]

[1.flat]
out_front_x_offset = 150
out_after_x_offset = 180
in_front_x_offset = 40
in_after_x_offset = 80
x_pos_speed = 500
x_recip_speed = 250
out_up_y_offset = 220
out_down_y_offset = 100
in_up_y_offset = 150
in_down_y_offset = 150
y_pos_speed = 100
y_recip_speed = 300
out_z_front_offset = 150
out_z_after_offset = 200
in_z_front_offset = 150
in_z_after_offset = 150
z_back_speed = 15
z_zeroing_speed = 200
outside_total_cycles = 1
inside_total_cycles = 1
recip_reduce_distance = 0
x_status_offset = 100

[2]
sn = 2
type = "xn_side"
x_position = 1200
z_position = 5170
spray_num = 6
tracking = 0
y_move_min = 0
y_move_max = 500
axis_type = ["z", "y1", "x1", "r1", "y2", "x2", "r2", "y3", "x3", "r3", "y4", "x4", "r4", "y5", "x5", "r5", "y6", "x6", "r6"]
spray_radius = 0
x_status_offset = 100
out_front_x_offset = 150
out_after_x_offset = 280
in_front_x_offset = 100
in_after_x_offset = 100
out_up_y_offset = 200
out_down_y_offset = 200
in_up_y_offset = 100
in_down_y_offset = 100
out_z_front_offset = 200
out_z_after_offset = 200
in_z_front_offset = 100
in_z_after_offset = 100
z_back_speed = 15
x_pos_speed = 500
x_recip_speed = 120
y_pos_speed = 100
y_recip_speed = 150
z_zeroing_speed = 200
outside_total_cycles = 2
inside_total_cycles = 2
recip_reduce_distance = 100
install_orietation = "right"
max_limit_speed = [250, 500, 500, 160]
min_limit_pos = [0, 0, 0, -180]
max_limit_pos = [900, 900, 900, 180]
origin_pos = [1120, 1420, 1720, 2020, 2320, 2620]
safe_pos = [0, 0, 0, 0]

[2.flat]
out_front_x_offset = 150
out_after_x_offset = 180
in_front_x_offset = 40
in_after_x_offset = 80
x_pos_speed = 500
x_recip_speed = 250
out_up_y_offset = 220
out_down_y_offset = 100
in_up_y_offset = 150
in_down_y_offset = 150
y_pos_speed = 100
y_recip_speed = 300
out_z_front_offset = 150
out_z_after_offset = 200
in_z_front_offset = 150
in_z_after_offset = 150
z_back_speed = 15
z_zeroing_speed = 200
outside_total_cycles = 1
inside_total_cycles = 1
recip_reduce_distance = 0
x_status_offset = 100
