[0]
sn = 0
type = "xn_updown2"
x_position = 1085
z_position = 4750
spray_num = 2
tracking = 0
y_move_min = 0
y_move_max = 300
axis_type = ["y1", "x1", "y2", "x2"]
spray_radius = 0
x_status_offset = 100
out_front_x_offset = 150
out_after_x_offset = 280
in_front_x_offset = 100
in_after_x_offset = 100
out_up_y_offset = 200
out_down_y_offset = 200
in_up_y_offset = 100
in_down_y_offset = 100
out_z_front_offset = 200
out_z_after_offset = 200
search_front_z_offset = 500
search_after_z_offset = 500
in_z_front_offset = 100
in_z_after_offset = 100
z_back_speed = 0
x_pos_speed = 500
x_recip_speed = 120
y_pos_speed = 100
y_recip_speed = 200
z_zeroing_speed = 100
outside_total_cycles = 1
inside_total_cycles = 1
recip_reduce_distance = 100
install_orietation = "left"
max_limit_speed = [500, 500]                 # Y, X
min_limit_pos = [0, 0]                       # Y, X
max_limit_pos = [1000, 900]                  # Y, X
origin_pos = [1020, 1320]                    # Y1, Y2
safe_pos = [0, 0]                            # Y, X

[1]
sn = 1
type = "out_2d_servo"
x_position = 0
z_position = 4970
spray_num = 1
tracking = 0
y_move_min = 0
y_move_max = 300
axis_type = ["y", "x"]
spray_radius = 0
x_status_offset = 0
out_front_x_offset = 200
out_after_x_offset = 100
in_front_x_offset = 100
in_after_x_offset = 100
out_up_y_offset = 100
out_down_y_offset = 100
in_up_y_offset = 100
in_down_y_offset = 100
out_z_front_offset = 70
out_z_after_offset = 100
search_front_z_offset = 500
search_after_z_offset = 500
in_z_front_offset = 100
in_z_after_offset = 100
z_back_speed = 100
x_pos_speed = 100
x_recip_speed = 100
y_pos_speed = 100
y_recip_speed = 100
z_zeroing_speed = 100
outside_total_cycles = 2
inside_total_cycles = 2
recip_reduce_distance = 0
install_orietation = "left"
max_limit_speed = [500, 500]                 # Y, X
min_limit_pos = [0, 0]                       # Y, X
max_limit_pos = [1000, 1000]                 # Y, X
origin_pos = [0]
safe_pos = [0, 0]                            # Y, X

[2]
sn = 2
type = "xn_updown2"
x_position = 1085
z_position = 4750
spray_num = 2
tracking = 0
y_move_min = 0
y_move_max = 300
axis_type = ["y1", "x1", "y2", "x2"]
spray_radius = 0
x_status_offset = 100
out_front_x_offset = 150
out_after_x_offset = 280
in_front_x_offset = 100
in_after_x_offset = 100
out_up_y_offset = 200
out_down_y_offset = 200
in_up_y_offset = 100
in_down_y_offset = 100
out_z_front_offset = 200
out_z_after_offset = 200
in_z_front_offset = 100
in_z_after_offset = 100
search_front_z_offset = 500
search_after_z_offset = 500
z_back_speed = 0
x_pos_speed = 500
x_recip_speed = 120
y_pos_speed = 100
y_recip_speed = 200
z_zeroing_speed = 100
outside_total_cycles = 1
inside_total_cycles = 1
recip_reduce_distance = 100
install_orietation = "right"
max_limit_speed = [500, 500]                 # Y, X
min_limit_pos = [0, 0]                       # Y, X
max_limit_pos = [1000, 900]                  # Y, X
origin_pos = [1020, 1320]                    # Y1, Y2
safe_pos = [0, 0]                            # Y, X

[3]
sn = 3
type = "out_2d_servo"
x_position = 0
z_position = 4970
spray_num = 1
tracking = 0
y_move_min = 0
y_move_max = 300
axis_type = ["y", "x"]
spray_radius = 0
x_status_offset = 0
out_front_x_offset = 200
out_after_x_offset = 100
in_front_x_offset = 100
in_after_x_offset = 100
out_up_y_offset = 100
out_down_y_offset = 100
in_up_y_offset = 100
in_down_y_offset = 100
out_z_front_offset = 70
out_z_after_offset = 100
in_z_front_offset = 100
in_z_after_offset = 100
search_front_z_offset = 500
search_after_z_offset = 500
z_back_speed = 100
x_pos_speed = 100
x_recip_speed = 100
y_pos_speed = 100
y_recip_speed = 100
z_zeroing_speed = 100
outside_total_cycles = 2
inside_total_cycles = 2
recip_reduce_distance = 0
install_orietation = "right"
max_limit_speed = [500, 500]                 # Y, X
min_limit_pos = [0, 0]                       # Y, X
max_limit_pos = [1000, 1000]                 # Y, X
origin_pos = [0]
safe_pos = [0, 0]                            # Y, X
